name: CI
on:
    workflow_dispatch:

jobs:
    build_apk:
        name: Build APK
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2

            - uses: actions/setup-java@v1
              with:
                  java-version: "11.x"

            - uses: subosito/flutter-action@v1
              with:
                  channel: "stable"

            - name: Pub get
              run: flutter pub get

            - name: Flutter Clean
              run: flutter clean

            - name: Building apk
              run: flutter build apk

            - name: Renaming apk
              working-directory: ./build/app/outputs/flutter-apk/
              run: mv app-release.apk custom_navbar.apk

            - name: Pushing changes
              uses: GuillaumeFalourd/git-commit-push@v1.3

            - name: moving apk to artifact
              uses: actions/upload-artifact@v2.2.0
              with:
                  name: apk
                  path: ./build/app/outputs/flutter-apk/custom_navbar.apk
                  if-no-files-found: error
